### ISSUE TITLE
redundant linker flag

### ISSUE THREAD

**Issue by kpcyrd** [erickt/rust-zmq#196] opened 2017-08-04 14:21 UTC
```
   Compiling serde_derive v1.0.1
warning: redundant linker flag specified for library `zmq`

   Compiling serde_derive v0.9.15
   Compiling zmq v0.8.2
```
I've spotted this a few time now and thought I'd let you know :)

**Comment by rotty** [comment] 2017-08-06 18:28
Thanks -- I've noticed this as well, but haven't yet looked into it. However, the solution suggested by the SDL2 bindings (i.e. removing the supposedly superfluous `#[link(..)]` attribute) breaks the windows build, (see #197). Any suggestions welcome!

**Comment by rotty** [comment] 2019-05-27 16:38
I can no longer reproduce this on the current `master` branch (commit c14d5b00), using `rustc 1.35.0 (3c235d560 2019-05-20)`. I tried to reproduce with an older commit, but the problem was gone there as well. Maybe this has been fixed in the toolchain.

**Closed by rotty** 2019-05-27 16:38 UTC
