### ISSUE TITLE
Getting data from C++ program

### ISSUE THREAD

**Issue by johnfercher** [erickt/rust-zmq#105] opened 2016-11-09 22:16 UTC
I have a server sending data using ZMQ writed in C++ and a want to retrieve this data using a program writed in Rust. I'm trying to adapt the https://github.com/erickt/rust-zmq/blob/master/examples/zguide/weather_client/main.rs but without success. It's a simple problem, may you help me?

**Here is the code used to create the server in C++**
```
context = new zmq::context_t(1);
socket = new zmq::socket_t(*context, ZMQ_PUB);
socket->bind(addr_server_multicast.c_str());
```

**Here is the code used in the server to send the data**
```
zmq::message_t request (msg_str.size());
memcpy ((void *) request.data (), msg_str.c_str(), msg_str.size());
socket->send(request);**
```

**Here is the code used to create the client in C++, which I want to write in Rust**
```
context = new zmq::context_t(1);
socket = new zmq::socket_t(*context, ZMQ_SUB);
socket->connect(addr_client_multicast.c_str());
socket->setsockopt(ZMQ_SUBSCRIBE, "", 0);
```

**Here is the code used in the client to get the data**
```
zmq::message_t request;
socket->recv(&request, 0); //  Wait for next request from client
std::string msg_str(static_cast<char*>(request.data()), request.size());
```

**Here is the code which I trying the retrieve the data in Rust**
```
let mut context = zmq::Context::new();
let mut subscriber = context.socket(zmq::SUB).unwrap();
assert!(subscriber.connect("tcp://localhost:5555").is_ok());

let filter = "10001".to_string();
assert!(subscriber.set_subscribe(filter.as_bytes()).is_ok());

loop {
    println!("reading");
    let string = subscriber.recv_string(0).unwrap().unwrap();
    println!("readed");
}
```

The rust program stops after print **reading**.

**Comment by rotty** [comment] 2016-11-11 13:58
Are you sure that your subscription matches the data sent? In the C++ example, you use an empty byte sequence with ZMQ_SUBSCRIBE, whereas in Rust you use "10001".

**Comment by johnfercher** [comment] 2016-11-11 14:13
I solve it, the problem was the this filter "10001", I put "" and worked.

**Comment by rotty** [comment] 2016-11-12 10:39
Note that you can also use bytestring syntax to tighten your code, i.e. just use `b""` instead of `"".to_string().as_bytes()`, which you are effectively doing above.

Also, please close the ticket if you feel the issue is resolved.

**Comment by rotty** [comment] 2016-11-16 16:03
Closing, as this was not an issue with `rust-zmq`.

**Closed by rotty** 2016-11-16 16:03 UTC
