### ISSUE TITLE
Hangs when returning a zmq::Socket

### ISSUE THREAD

**Issue by hanckmann** [erickt/rust-zmq#107] opened 2016-11-13 09:04 UTC
See this code:
`
// http://pastebin.com/dCVLHa4a

    extern crate zmq;

    use std::io::Write;

    fn write_sting_oke() {
        let topic_endpoint = "tcp://*:5556";

        let mut ctx = zmq::Context::new();
        let mut socket = match ctx.socket(zmq::PUB) {
          Ok(socket) => { socket },
          Err(e) => { panic!(e) }
        };

        // match socket.connect(&topic_endpoint) {
        //   Ok(()) => (),
        //   Err(e) => panic!(e)
        // };
        assert!(socket.bind(topic_endpoint).is_ok());
        
        let topic = "test";
        let message = "testing-oke-thing";
        let update = format!("{} {}", topic, message);
        socket.send(update.as_bytes(), 0).unwrap();
    }

    fn pub_socket() -> zmq::Socket {
        let topic_endpoint = "tcp://localhost:5556";

        let mut ctx = zmq::Context::new();
        let mut socket = match ctx.socket(zmq::PUB) {
          Ok(socket) => { socket },
          Err(e) => { panic!(e) }
        };

        match socket.connect(&topic_endpoint) {
          Ok(()) => (),
          Err(e) => panic!(e)
        };
        writeln!(std::io::stderr(), "return socket (will fail)").unwrap();
        socket
    }

    fn write_sting_fail() {
        writeln!(std::io::stderr(), "before pub_socket").unwrap();
        let mut socket = pub_socket();
        writeln!(std::io::stderr(), "after pub_socket").unwrap();

        let message = "test testing-fail-thing".as_bytes();

        match socket.send(message, 0) {
          Ok(()) => (),
          Err(e) => panic!(e)
        };
    }

    fn main() {
        println!("Hello World!");
        println!("Will do");
        write_sting_oke();
        println!("Will hang");
        write_sting_fail();
    }
`
The function "pub_socket()" never returns and hangs.
I also created a gdb stacktrace: http://pastebin.com/BKpdJPUv

Is there

**Comment by birkenfeld** [comment] 2016-11-13 09:27
That's because zmq_ctx_destroy will block until all its sockets are closed. Currently the Rust wrapper doesn't encode the "socket needs context" dependency in the types in order to prevent this.

Pull request #65 would fix this, it wouldn't allow you to return a Socket when the Context is dropped at the end of the function.

**Comment by birkenfeld** [comment] 2016-11-13 09:33
Ah yes, duplicate of #92.

**Comment by rotty** [comment] 2016-11-16 16:33
@hanckmann: I've now merged #96, which should make this code work. A `zmq::Context` will now be kept alive as long there is any socket referencing it. As a side note: you might want to have a look at <https://github.com/erickt/rust-zmq/commit/87357c34cf698779fd3a801c8f2af9d75c2d60c2>. This simplification also applies to your code.

**Comment by rotty** [comment] 2016-11-16 16:39
As there's now a test case that checks for the pattern exposed in this code, and the code provided in #92 also worked, I'm now closing this.

**Closed by rotty** 2016-11-16 16:39 UTC
