### ISSUE TITLE
Implement the `Write` and `Read` traits for sockets(?)

### ISSUE THREAD

**Issue by nagisa** [erickt/rust-zmq#254] opened 2019-04-18 15:25 UTC
It would be great if we could make ∅MQ to blend in with the usual I/O streams. Some of this could be achieved with `Write` and `Send` trait impls(?).

**Comment by birkenfeld** [comment] 2019-04-18 15:45
Dupe of https://github.com/erickt/rust-zmq/issues/238 - in short, the semantics does not match.

The exception may be ZMQ_STREAM sockets, which are meant for interfacing with non-zmq TCP sockets.

**Closed** 2019-04-18 16:14 UTC
